
tro:kapgate_pa2_tro.c
	gcc -o kapgate_pa2_tro kapgate_pa2_tro.c -lm

stra:kapgate_pa2_stra.c
	gcc -o kapgate_pa2_stra kapgate_pa2_stra.c

floyd:kapgate_pa2_floyd.c
	gcc -o kapgate_pa2_floyd kapgate_pa2_floyd.c


